pin the version of tzlocal.
The test suite started failing with exceptions like:

Traceback (most recent call last):
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/tests/testuploading.py", line 1064, in test_rollback_bad_rows
    upload_results = do_upload_csv(self.collection, reader, self.example_plan, self.agent.id)
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload.py", line 182, in do_upload
    bind_result = upload_plan.disambiguate(da).bind(collection, row, uploading_agent_id, _auditlog, cache)
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload_table.py", line 107, in bind
    result_ = record.bind(collection, row, uploadingAgentId, auditlog, cache)
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/tomany.py", line 60, in bind
    parsedFields, parseFails = parse_many(collection, self.name, self.wbcols, row)
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/parsing.py", line 52, in parse_many
    for fieldname, colopts in mapping.items()
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/parsing.py", line 52, in <listcomp>
    for fieldname, colopts in mapping.items()
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/parsing.py", line 75, in parse_value
    result = _parse(collection, tablename, fieldname, colopts, value_in.strip())
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/parsing.py", line 122, in _parse
    return parse_date(table, fieldname, value, colopts.column)
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/parsing.py", line 221, in parse_date
    ).get_date_data(value, date_formats=['%d/%m/%Y', '00/%m/%Y'])
  File "/home/ben/src/specify/seven/next-release/ve/lib/python3.6/site-packages/dateparser/date.py", line 410, in get_date_data
    res = parse_with_formats(date_string, date_formats or [], self._settings)
  File "/home/ben/src/specify/seven/next-release/ve/lib/python3.6/site-packages/dateparser/date.py", line 155, in parse_with_formats
    date_obj = apply_timezone_from_settings(date_obj, settings)
  File "/home/ben/src/specify/seven/next-release/ve/lib/python3.6/site-packages/dateparser/utils/__init__.py", line 125, in apply_timezone_from_settings
    date_obj = tz.localize(date_obj)
AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'localize'

I believe it is because dateparser requires an unpinned version of
tzlocal so the build started pulling version 3.0 which was release
recently. Apparently that version causes problems so I am pinning it
to the previous version.